services:
  - type: web
    name: c-book-proyecto
    env: node
    region: ohio
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://c-book-proyecto.vercel.app
      - key: CORS_ALLOWED_ORIGINS
        value: https://c-book-proyecto.vercel.app
      - key: SESSION_SECRET
        generateValue: true
      - key: RESET_PASSWORD_SECRET
        generateValue: true
      - key: SESSION_COOKIE_SAME_SITE
        value: none
      - key: SESSION_COOKIE_SECURE
        value: "true"
      - key: NODE_ENV
        value: production
